### ISSUE TITLE
Function description display

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#12]
opencontracts.contractFunctions[i].description is not being displayed. if it is defined, display a prompt box titled 'description' as the first box, and give it a unique little icon just like the other boxes, and use it as its content.

**Comment by l-monninger** [comment]
@Jonas-Metzger  Are you saying you want this as an item in the log?

**Comment by Jonas-Metzger** [comment]
Yes! As the first item

**Comment by open-contracts** [comment]
Great! Only one thing: description should not be displayed if none exists.
![image](https://user-images.githubusercontent.com/90533597/142050659-6cf29c20-3bc3-439f-88ac-05b41df39157.png)

**Comment by open-contracts** [comment]
great!
