### ISSUE TITLE
MetaMask animation speed

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#17]
If possible, speed up the metamask animation. It's much slower than the actual time it takes to connect metamask (right?), which would be unnecessary annoyance.

**Comment by l-monninger** [comment]
1. It's possible to speed up the check mark animation and fly to page right. Those animations begin when MetaMask has successfully loaded.
2. It's also possible to speed up the migrate to page top animation that occurs before the check mark, though this animation is aborted if MetaMask loads faster than animation plays.

@Jonas-Metzger  Do you want both?

**Comment by open-contracts** [comment]
only 1! 2. doesn't waste time, and it looks good right now
