### ISSUE TITLE
fist keypress in input prompt is ignored

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#20]
try out the venmoPurchase function, click into the text field of the input and start typing. the first keypress is not registered, the first letter does not show up in the box.

**Comment by l-monninger** [comment]
I was unable to replicate this on any browser. Was this happening for you every time?

**Comment by l-monninger** [comment]
@Jonas-Metzger

**Comment by open-contracts** [comment]
most recent website works now!

**Comment by l-monninger** [comment]
I was finally able to replicate...

**Comment by open-contracts** [comment]
awesome! fixed it
