### ISSUE TITLE
why does yarn install ethers and web3 dependencies

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#21]
client-protocol should already contain all required dependencies?

**Comment by l-monninger** [comment]
For types.

**Comment by l-monninger** [comment]
And, for the general wallet check.

**Comment by open-contracts** [comment]
types makes sense for ethers, but I guess you should freeze it at the same version as the `client-protocol` (5.4.6).
Web3 does not make sense for me yet, can you elaborate? It's not a dependency of `client-protocol` after all, and `client-protocol` already takes care of the wallet. If you're using it to grab the users address, you can just get it from `opencontracts.signer.getAddress()`

**Comment by open-contracts** [comment]
Related to https://github.com/open-contracts/open-contracts.github.io/issues/16

**Comment by open-contracts** [comment]
Web3 is a mess of a package that should not really be used in fresh projects anymore imo. Ethers is much better maintained. And using both is bad practice.

Another reason why you shouldn't implement your own web3 is bc I am planning to add other wallets in the near future (who tend to have their own init quirks), and if you're relying on something other than `client-protocol`, you need to keep updating the website for stuff like this.
