### ISSUE TITLE
deactivate interactive elements which can only used once

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#24]
In particular:

- the "call function" button should only be clickable once, then be greyed out
- every enclave input prompt (and its submit button) should become greyed out once its submit button is triggered

Of course, the "Reset log" button should reset everything again.

**Comment by l-monninger** [comment]
Completely disabling the call button after the initial call will render the Reset log button defunct. The log will be reset. But, you won't be able to use the function again until you've navigated away, so what's the point?

What if instead I promisify the whole procedure. While running, the button is disabled and features a spinner. When complete the button is available once more. Wouldn't have to change anything about the protocol just additional abstraction in the Dapp state that I maintain.

**Comment by l-monninger** [comment]
I think it might be better to promisify the whole procedure and reenabled Call on complete. If we just disable it until `Reset log` is called, the user would never be able to maintain the state of previous attempts for cross reference. Plus, semantically, the function call isn't disabled and awaiting user reset so much as it is in progress and awaiting completion.
