### ISSUE TITLE
reset behaviour

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#25]
I don't know what the "reset args" button in the error prompts does (if it does anything), but the args should also be reset by "Reset log". So remove the "reset args" button and rename the "reset log" button to simply be "reset". One unified way of resetting everything (that's always available) will be more intuitive for users.

**Comment by l-monninger** [comment]
@Jonas-Metzger Reset log is supposed to be the other half of Reset args that removes any other puts. It looks like one of the changes to the textInput prevents is preventing either button from removing the text from the state of the text input. I will change.

**Comment by l-monninger** [comment]
I actually think that it would restrict what the user can do to make these buttons the same. If they want to clean out the log, but keep their old arguments, they can just use Reset log. If they want to keep track of the old output but try new inputs, they can just use Reset args.

**Comment by Jonas-Metzger** [comment]
We need a 'reset' button that truly resets the state. Both visually (log) and under the hood (state of opencontracts object). So like a page refresh, but keeping the current function open.

This is the only button I would ever want to use, and ever suggest anyone else using, given how thinks work under the hood.

Resetting the visuals while keeping opencontracts state, or vice versa, is a recipe for confusion at least, and unhandled/unanticipated bugs at worst. Plus, it's not that useful. 

I'm also anticipating users who will be confused what we mean by the words "args" and "log". honestly, I'm personally not even sure what exactly gets reset with each. This is aggravated by the mismatch between visuals and under the hood. A unified "Reset" is pretty clear tho.

**Comment by l-monninger** [comment]
I agree with the sentiment on simplicity. But, I don't agree atm with the conclusion, especially if we completely disable the call button after initial call until the state is reset. Then, no one can ever reuse their inputs. 

Regardless, I have removed.

**Comment by open-contracts** [comment]
Ah I see! Yeah I think it makes sense to keep the input fields filled in, no issue with that! If that was the only thing the reset log button doesn't reset, all good! I was worried more about the state of the opencontracts object not being reset (=recreated). Happy to keep the former as long as the latter is reset. But all of this is a low priority ofc

**Comment by l-monninger** [comment]
@Jonas-Metzger  Yeah, let's just stick with how it is now. Single reset.
