### ISSUE TITLE
error on successful metamask transaction

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#27]
just did a metamask transaction. It went through, but the page turned white, url changed to /#/error and and received this error in the console:
![image](https://user-images.githubusercontent.com/90533597/142128918-fded1a89-9125-4876-b91d-75c3b5b23be3.png)

**Comment by l-monninger** [comment]
@Jonas-Metzger This was on the built version?

**Comment by open-contracts** [comment]
I added some transaction result parsing on the client-protocol side, now the error disappeared.
