### ISSUE TITLE
url updates don't get recognized

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#28]
clicking submit successfully changes the url to /#/user/repo/ref, but I need to do a manual refresh to actually see the page. 

The same behavior happens simply when manually entering a url (e.g. to a different contract) in your browser, if you're already on the website.  It does not get applied when hitting enter once. you have to click into the url bar again, then hit enter again, for it to be applied.

**Comment by open-contracts** [comment]
ah the other case is simply when entering a url (e.g. to a different contract) in your browser. It does not get applied when hitting enter once. you have to click into the url bar again, then hit enter again, for it to be applied.

**Comment by l-monninger** [comment]
@Jonas-Metzger f915481 fixes the initial submit issue for me.

**Comment by l-monninger** [comment]
@Jonas-Metzger e929e48 fixes the manual entry issue for me.

**Comment by l-monninger** [comment]
33s boy

**Comment by open-contracts** [comment]
awesome!!
