### ISSUE TITLE
display f.waitHandler to the user

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#29]
The client-protocol allows the frontend to customize the `f.waitHandler(seconds, message)` function. By default (=right now), it just prints a warning to the console.

When called, display an **ephemeral** log element, which

- respects the same layout as other log elements
  - has a little clock/timer or so as icon
  - is titled 'Loading'
  - displays the message as content
- Displays a loading bar that completes after `seconds` 
- the seconds are a best guess, not a hard threshold - so it can look like it's still doing something after completing

   
Important: By Ephemeral, I mean that it should disappear again as soon as a new element is added to the log. In particular, the function may (or may not) be called twice, in which case only the most recent one should be displayed to the user. It should also disappear once other stuff (messages, errors) are coming in.

**Comment by l-monninger** [comment]
@Jonas-Metzger I'm not receiving any updates rn on this or old.

**Comment by l-monninger** [comment]
@Jonas-Metzger  I feel like I also want some waiting prompts in between inputs. Any thoughts?

**Comment by open-contracts** [comment]
looks awesome! great work

**Comment by open-contracts** [comment]
re input prompts, I don't think it quite makes sense for us - the delay depends on the logic that oracle.py executes, which is arbitrary. we could add a spinning circle or so add the bottom of the log while the websocket is open, which suggests that we're still connected and the enclave is (supposedly) doing something
