### ISSUE TITLE
f.xpraHandler logic

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#30]
Check out the default [f.xpraHandler]( https://github.com/open-contracts/client-protocol/blob/03d924ac882a908aec2a398600c6debc9349dd34/opencontracts.js#L392
):

![image](https://user-images.githubusercontent.com/90533597/142271221-bff6617f-cd36-4a2f-90f8-f5ac58be36f0.png)

It does two things that are currently not done by the frontend, I think:

- it automatically closes the new window when xpraExit resolves (because of browser restrictions, JS code can only close windows itself opened - so the xpra window can't even close itself. that's why the f.xpraHandler has to implement this step)
- it detects if a popup blocker blocked the window creation. If the condition in Line 397 is satisfied, we should print a warning inside the xpra log prompt. The user could then change its browser setting and click the 'launch' button again.

**Comment by l-monninger** [comment]
You want both to remain in?

**Comment by open-contracts** [comment]
yes, perfect!
