### ISSUE TITLE
nicer theme

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#31]
Okay I think I found a way to get from the current design to something much nicer with minimal changes:

1. Remove all border lines from all elements (tabs, buttons, prompts, function boxes)

![image](https://user-images.githubusercontent.com/90533597/142278610-2a003762-8e11-4553-9548-30fcf0f53a1d.png)

2. Add shadows to everything! Let's put them everywhere we had lines, basically. Keep the shadows tight/minimal for buttons, but make them strong for the tabs and medium for the log prompts and function boxes. Try using a similar angle as below, where there is shadow around all sides of the object, but more below than above.

![image](https://user-images.githubusercontent.com/90533597/142280230-4d82afde-cca1-4f3f-affe-50ae281c89c5.png)

3. Make the active tab grey a bit darker than what it is right now, but maybe a bit lighter than in the picture above. The inactive tab should keep the current light grey. Also, let's switch back to having the grey tab area having the minimal height again (i.e. **_not extending infinitely downwards_**). This will go nice with the shadows, and make it look more like physical object hovering above the page. Also, make sure all tab corners (inside+outside) are rounded with the same radius. Currently some are sharp.

4. Change the hover animation for tabs: instead of making them black, make them somewhere in between the current, light  'inactive tab grey' and the new, darker 'active tab grey' on hover. This will be more fluid.

5. Change the hover animation for function tiles: make it grow a bit on hover (like the tiles on opencontracts.io, but a bit less pronounced), and strengthen its shadow. Smoothly reverse this animation when the mouse moves away. Don't do a color change (right now it turns black).

6. If it looks nice, I think we could go for "grow a bit+strenghten shadow" as hover animation for all buttons. The growth should be minor, most of the emphasis should come from the shadows.

I think this will look nice!

**Comment by l-monninger** [comment]
@Jonas-Metzger This does look better! The dark gray background for the selected content tile is a bit rough though.

**Comment by open-contracts** [comment]
@l-monninger it's starting to look really cool man! makes me very happy 😃 

yeah I guess we could try a somewhat brighter gray, but I'm quite happy with the current colors already! 

Looking forward to seeing how it looks when you add strong shadows to the active tab, and make it adaptive/minimal height again and round out the sharp corners (point 3.).
