### ISSUE TITLE
return prompt fixes

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#32]
The current frontend assumes that all contract functions return an output, but this is slightly incorrect.

Check out  https://open-contracts.github.io/#/open-contracts/sample-contract.

If you call the 'get string' function, with a messageValue=0, its contract logic will throw an error:
![image](https://user-images.githubusercontent.com/90533597/142546452-8a9fe7d2-f155-4c17-bf72-70e46036db90.png)
In this case, the result object should not be displayed (even though the function call succeeds).

Finally, for all function calls which actually trigger an Ethereum transaction (unlike e.g. view or pure functions), the function call will eventually return "Transaction Confirmed. (...)", once it was successfully added to the blockchain (or call the errorHandler). 

Currently, this will look as follows:
![image](https://user-images.githubusercontent.com/90533597/142549059-75caec28-f19f-4368-8fad-4f1c334f3b08.png)

This doesn't really make sense since the returned string is not actually the result of a computation. The result prompt currently also uses a very different layout from the other log prompts, which is a subproblem of https://github.com/open-contracts/open-contracts.github.io/issues/6. 

So I would prefer if we used "y" as an icon next to the "Result" prompt title (just like x for inputs and (!) for errors), and removed the "=". Also make sure that your using the same (non-bold) font (same font size too) for "Result" as for all other log prompt titles (which are currently not harmonized yet, see https://github.com/open-contracts/open-contracts.github.io/issues/6 and apply the same criteria to the result prompt).

**Comment by l-monninger** [comment]
@Jonas-Metzger Sorry, forgot to tag one of my commits here. This should be resolved/close-to resolved now.

**Comment by open-contracts** [comment]
awesome, looks resolved to me!
