### ISSUE TITLE
support markdown text rendering 

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#33]
@Jonas-Metzger Do you want a link for this?:
<img width="941" alt="Screen Shot 2021-11-19 at 7 59 54 PM" src="https://user-images.githubusercontent.com/79056955/142713830-f0ae94c0-b705-411d-a616-32d9ec6c0124.png">

**Comment by open-contracts** [comment]
yeah might be a good idea to add one eventually! the docs are still in the works right now. We could automatically run all error, notification and description text through a markdown parser, which allows for syntax like `[linkext](url)`. That would allow me to specify links in the client-protocol package, allow contract devs to display links if a contract.sol `require(condition, 'some message')` failed, send links with `enclave.print()` prompts in oracle.py, or specify links in the `f.description` fields

**Comment by l-monninger** [comment]
@Jonas-Metzger  I was thinking the same thing.

**Comment by l-monninger** [comment]
@Jonas-Metzger This is now supported.
