### ISSUE TITLE
disable text prompt bug

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#34]
At least with invalid input errors, the input field disabling misbehaves.
To reproduce, go to https://open-contracts.github.io/#/open-contracts/fiat-swap
and enter some invalid input e.g. in the  allowedHash function. When clicking "call function", the following error appears:
 
![image](https://user-images.githubusercontent.com/90533597/142775341-ebd7d957-6b75-43e4-8dd0-bc905197cbfc.png)

At this point the input fields are still useable (although they shouldn't be). When clicking "Reset" however, they become disabled (and fun fact: not emptied out! the button seems to only reset the log). The website becomes unusable until refresh.

The right behavior would be to have the "call button" always disable the input fields, and the "reset" button always re-enable them. Beyond that, it's not really important whether or not the "reset" button resets the input fields or not, either is fine with me.

**Comment by l-monninger** [comment]
@open-contracts Alright, so I am not getting this behavior consistently. But, I think I may have a solution.

**Comment by open-contracts** [comment]
seems to be working new! but it may have introduced an new bug. opening a new issue...
