### ISSUE TITLE
resizing window messes with oracle session

### ISSUE THREAD

**Issue by krishpop** [open-contracts/open-contracts.github.io#35]
Every time the window is resized while waiting for "Connecting to Oracle" to finish, the progress bar resets

**Comment by open-contracts** [comment]
in fact, the whole oracle session get's messed up if the window is resized. new prompts sometimes don't show up anymore. Happens rather consistently when resizing during the loading bar, but also during an input prompt, etc... 

What's causing this issue @l-monninger ?

**Comment by open-contracts** [comment]
Hey @l-monninger this is a really high priority issue. Any resizing, even if its just opening the console can make the enclave essentially inaccessible, requiring to refresh the page and a full enclave reboot for it to become available again. Happens quite consistently during loading animations, especially enclave boots.

**Comment by l-monninger** [comment]
@Jonas-Metzger I believe this is resolved. But, there are some weird lags and disabled inputs. Still trying to determine if they are related.

**Comment by l-monninger** [comment]
@Jonas-Metzger Lags are largely resolved and disabled inputs as well. If I reset the args before completing the interactive session, should I expect that the enclave will be busy? Or, should I be able to handle this too?

**Comment by l-monninger** [comment]
@Jonas-Metzger Wanted to check on the above again?

**Comment by open-contracts** [comment]
this is much better! One thing that would be great to fix: the loading bars become useless after the windows are resized, but fortunately this only messes with the visuals. I'm guessing the loading bar speed is defined as a constant once it starts moving, or so. Instead, its position should be defined as a percentage of the width, which gradually increases towards 100%.

**Comment by l-monninger** [comment]
@Jonas-Metzger Yeah, I've been meaning to fix this, but keep forgetting to when I see it. I believe I remember the solution should be something along these lines. I'll check after I do the centralized.

**Comment by open-contracts** [comment]
Awesome! While your at it, try to compute the percentage via the difference between the current timestamp and the timestamp at which the bar was initialized. This hopefully fixes the current bug where the bar stops when the user switches into a different tab, and resumes where it stopped when they come back, rather than where it should be at this point.
