### ISSUE TITLE
Oracledata loading bug

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#37]
Check out the 'claim' function here: https://open-contracts.github.io/#/open-contracts/weather-insurance/main

There should be 5 files, but the counter counts 3/3, 4/4, then 5/5.

What makes this bug severe is that 'call function' can already be clicked before the counter reaches 5/5 - in which case the oracle connection will fail, without an obvious reason

**Comment by l-monninger** [comment]
@Jonas-Metzger  Almost have this fixed.

**Comment by l-monninger** [comment]
@Jonas-Metzger I believe this is resolved.
