### ISSUE TITLE
log does not accumulate anymore

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#38]
unfortunately, new log boxes always overwrite the previous one, such that there is only ever one box at once. 
![image](https://user-images.githubusercontent.com/90533597/149316464-79777a5d-e059-47b0-9bb2-82beb6ed6bbc.png)

Previous log boxes should only get overwritten if it is a f.waitHandler loading bar.

**Comment by l-monninger** [comment]
@Jonas-Metzger  Yeah, sorry, that was really dumb of me. Should be resolved now.
