### ISSUE TITLE
weird behavior upon result

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#39]
click on 

https://opencontracts.io/#/open-contracts/proof-of-id

then on the "getID" function, enter my address "0xc3e9591EDB56DcC951D50CD5002108e9d8968410", click 'call function'
and watch what happens.

The interface switches the function, and the getID function gets renamed into "Result" (?!)
![image](https://user-images.githubusercontent.com/90533597/149319714-741f031c-18e0-4976-863f-3a30b99449af.png)
Clicking on the Result function, we see the right output.

The behavior for errors is also super weird. Enter the invalid address "0xc3e9591EDB56DcC951D50CD5002108e9d8968411" and call, which yields an invalid checksum error (as it should). But then Reset, and enter the invalid "0xc3e9591EDB56DcC951D50CD5002108e9d8968411" again, and the interface renames the function again. Clicking on the "Result" tab this time however, there is no output. 

Also make sure an invalid input -> reset -> valid input sequence works as expected.

Could we do a little code review and reflect on what coding pattern caused this issue? I wonder if things are more complicated than they need to be with the current frontend logic here.

**Comment by l-monninger** [comment]
@Jonas-Metzger I'm pretty sure this is just a result of things not being refactored properly. I should probably start writing unit tests to keep myself in line.

**Comment by l-monninger** [comment]
@Jonas-Metzger  Yeah, just forgot to remove a prop name.

**Comment by l-monninger** [comment]
@Jonas-Metzger I also reverted the reset button to preserving the inputs. Let me know if that's what you want.

**Comment by open-contracts** [comment]
yes, that's perfect!
