### ISSUE TITLE
Loading displays between oracle awaits.

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#41]
Lag between waiting `waiting : false` and `oracleInput` display needs to be resolved, logically or visually.

**Comment by open-contracts** [comment]
I guess as a one-fits-all solution to delays whenever the user can't do anything, we could add a "."->".."->"..."->"."->".."->"..." kind of animation, similar to a chat app where "the other user is typing something". Could address https://github.com/open-contracts/open-contracts.github.io/issues/40 with this as well.

**Comment by open-contracts** [comment]
I think I added one now
