### ISSUE TITLE
(!!) Call button is permanently disabled right now

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#43]
not needed anymore, enclave downloads directly. reduced waiting times by 20x on low upload connections. better for mobile too.

**Comment by Jonas-Metzger** [comment]
You removed the load button but didn't allow the call button to be pressed without it.

**Comment by open-contracts** [comment]
@l-monninger this is urgent, oracles are unusable now. Krishnan can't test his updates to the backend while this isn't resolved

**Comment by l-monninger** [comment]
@Jonas-Metzger I'm still getting that testnet error, even though I pulled the new client. I can only guess what this actually doing. But, take a look now. I'm going to put everything on separate branch hereafter.

**Comment by open-contracts** [comment]
The error comes from an interface.json that has an incorrect/outdated structure. Make sure you're pointing the dapp to one of the 5 sample contracts linked to from opencontracts.io
