### ISSUE TITLE
entering a repo on front page directs to empty contract page

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#45]
go to https://dapp.opencontracts.io, enter a "open-contracts/fiat-swap", click 'submit' -> empty page with url "https://dapp.opencontracts.io/#/open-contracts/fiat-swap/main"

enter "https://dapp.opencontracts.io/#/open-contracts/fiat-swap/main" into url bar directly -> hit enter -> everything works

**Comment by l-monninger** [comment]
@Jonas-Metzger Neither are working for me locally because of `CLIENTERROR: YOUR METAMASK IS SET TO ROPSTEN, WHICH IS NOT SUPPORTED BY THIS CONTRACT. SET YOUR METAMASK TO ONE OF: NAME,ADDRESS,DESCRIPTIONS,ABI`. What do I need to do? I thought Ropsten was our test net.

**Comment by Jonas-Metzger** [comment]
You need to pull from main. I changed the client protocol in a patchy way to simplify the open contracts repo structure, including interface.json. it breaks with the current assumptions of the frontend. The way I currently did it works for contracts (once you pull), but breaks in the "enter repo" frontpage. we should talk it over in person. Can you zoom today?

**Comment by l-monninger** [comment]
@Jonas-Metzger  I can Zoom today.

**Comment by l-monninger** [comment]
@Jonas-Metzger Do we need roll HEAD back a few commits, so Krishnan can keep working?

**Comment by open-contracts** [comment]
yep, that fixed it
