### ISSUE TITLE
reset after ethereum error

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#46]
while the reset button works much more reliably than before, there's still a failure case: 
try the "policyID" function of the [weather-insurance contract](https://app.opencontracts.io/#/open-contracts/weather-insurance) with the following inputs, which (correctly) yields an out-of-bounds error because 9999 doesnt fit into int8.
![image](https://user-images.githubusercontent.com/90533597/152594236-159d1997-a4d0-4ff7-8b99-0d10f15e2b2b.png)
(Reset-> replace 9999 with 9998 -> call again) works and correctly shows a new error message, but (Reset-> replace 9999 with 1 -> call again) shows nothing, instead of the correct result which would look as follows:
![image](https://user-images.githubusercontent.com/90533597/152594640-4f331bf8-d91b-433c-ad9e-4a8f5be9c582.png)

**Comment by l-monninger** [comment]
@Jonas-Metzger That's a weird one. FYI, my phone is donezo, so I can't whatsapp.

**Comment by Jonas-Metzger** [comment]
@l-monninger how can I reach you?

**Comment by l-monninger** [comment]
@Jonas-Metzger Best place is here. Back from Hawaii now and getting a new phone tomorrow.
