### ISSUE TITLE
Error message on MetaMask fail to connect

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#49]
@Jonas-Metzger The home page lacks an error messages when MetaMask fails. Would you like me to display any? Are we safe showing the actual web3 error messages in the early days?

**Comment by Jonas-Metzger** [comment]
If we can't detect metamask, we should display a page telling people what they need to do to get it running. A little explanation of why it's needed, and how to get it for browser/Android/ios
