### ISSUE TITLE
Roadmap to perfect mobile UX

### ISSUE THREAD

**Issue by Jonas-Metzger** [open-contracts/open-contracts.github.io#50]
This includes changes to the client-protocol and the enclave protocol. In involves a bunch of important steps.

We need to
- support a [Wallet Connect Signer](https://docs.walletconnect.com/) for ethersjs and switch the ethersjs provider over to an Infura API, and activate this automatically in any browser where metamask cannot be detected. 
- for decentralization, the Infura API is provided (and paid for) by (_any_) registry provider, which initially means only us 

--> now the dapp runs in any browser, and only when you want to submit a tx you {on laptops: scan a qr code that suggests a tx on any mobile wallet on your phone, on mobile: click a link that does the same}

- interactive session windows will likely have to happen embedded (=as overlay) inside the main tab due to poor mobile's tab-swiching UX and strict device policies which kill the ws connection in the background tab sometimes

- fix formatting for existing UI elements

- I have to come up with a dramatically better chromium solution for touch-only devices. Might have to replace xpra with an open-source version of [Viewfinder](https://github.com/crisdosyago/Viewfinder)

**Comment by open-contracts** [comment]
UI is pretty usable on metmask mobile browser now. let's revisit WalletConnect later.
