### ISSUE TITLE
prefill errors

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#55]
The prefill logic is causing bugs:

![image](https://user-images.githubusercontent.com/90533597/155864718-1e265143-d70a-47f8-8ec4-3f88676ab799.png)

1. need to remove of ignore the "/" before "#", currently it gets filled in automatically
2. it always seems to be reading from and writing to fname.0

**Comment by l-monninger** [comment]
@Jonas-Metzger Should be fixed now. The `.slice(0, -1)` on the `searchParams.get()` caused the inputs to be curtailed. If we want to allow for that slash, we can .replace the /'s. Search params are URI encoded.
