### ISSUE TITLE
branch is always parsed as "main"

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#57]
`github.com/#/open-contracts/ethereum-protocol/hub` gets supplied as `@git/open-contracts/ethereum-protocol/main`

i'll temporarliy fix this on the client protocol side by manually parsing the location. lmk when I can switch back.

**Comment by l-monninger** [comment]
@Jonas-Metzger  Did you also want the activeFunc bit in query params?

**Comment by open-contracts** [comment]
Let's leave that out for now. But I think the recent commit introduced a bug @l-monninger where the page doesn't load by itself if you come from the centralized website in a fresh browser session.  Needs a manual refresh.  Pls fix
