### ISSUE TITLE
Continuously Updated list of Todos

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#7]
List of bugs

**Comment by open-contracts** [comment]
~when using the form to enter open-contracts/fiat-swap and clicking submit, two /#/# get added to the url, causing an error~.

**Comment by open-contracts** [comment]
~add a vertical scroll bar to the right side of the page~

On firefox and brave, there are too many scrollbars:
![image](https://user-images.githubusercontent.com/90533597/140811873-be5c47c2-cd02-4cce-80db-a4b14940a74f.png)

**Comment by open-contracts** [comment]
Now there is a `opencontracts.contractDescription` string attribute, which should be displayed below the contract name. There's now also a `opencontracts.contractName` attribute, I don't know where you got the contract name before, but use this now instead.

**Comment by open-contracts** [comment]
`open-contracts.github.io/old` supports specifying the branch/ref, using `user/repo/ref` syntax. Could we add that in again?

**Comment by open-contracts** [comment]
If the user takes too long e.g. to respond to a user input request, the enclave will cancel the interaction, resulting in a closed websocket. We should display this. I will take care of letting the package throw an error in this case

![image](https://user-images.githubusercontent.com/90533597/141349580-a582e816-c13d-4c51-b072-df607454a56b.png)

**Comment by open-contracts** [comment]
Continuously-updated list of todos:
- the `user/repo/ref` syntax is not implemented correctly. Currently, the website always tries to load `interface.json` from the current main branch, instead it should be loaded from the `ref` branch/commit, and only default to `main` if `ref` isn't specified. Also make sure you're passing `ref` to the githubOracleDownloader. Also, the 'view on Github' button does not correctly use `ref` right now, causing it to fail in general.
- `opencontracts.contractDescription` should be displayed below the `opencontracts.contractName` (make sure you're actually using that variable, not sure where the contract name is currently coming from)
- Display the current function name next to "f_x" inside the tab, and make the tabs (and icons) larger such that the function name can be prominent and things are more touch friendly.
-  `opencontracts.contractFunctions[i].description`  is not being displayed. if it is defined, display a  prompt box titled 'description' as the first box, and give it a unique little icon just like the other boxes, and use it as its content.
- The title of the input prompt should be 'Inputs', not the function name (there are functions without inputs, in which case the input prompt should not be displayed - right now it is.). Change the play button icon to the 'x' (instead of displaying x next to every single input)
- Close all windows of your browser. Then visit the website. You'll get a metamask error, until the user manually opens metamask, enters their password, and refreshed. Compare this behavior to that of /old, where Metamask pops up automatically once the user clicks 'load contract', even in a fresh browser session. The reason is that you're calling `opencontracts = OpenContracts()` right when the website loads, and (I think) metamask blocks the request on window load in recent versions. Instead, change the metamask connection prompt slightly: try to call `opencontracts = OpenContracts()` but if it fails, instead of the current error, display a `connect metamask` button, which calls `opencontracts = OpenContracts()` again. Only if that fails, display the error message. This will also make sure the 'connect metamask' button only displays when it is needed: in a fresh browser session.
- If possible, speed up the metamask animation. It's much slower than the actual time it takes to connect metamask (right?), which would be unnecessary annoyance.

**Comment by l-monninger** [comment]
> If the user takes too long e.g. to respond to a user input request, the enclave will cancel the interaction, resulting in a closed websocket. We should display this. I will take care of letting the package throw an error in this case
> 
> ![image](https://user-images.githubusercontent.com/90533597/141349580-a582e816-c13d-4c51-b072-df607454a56b.png)


@Jonas-Metzger  Has this been taken care of in the package?

**Comment by l-monninger** [comment]
Closing this in favor of tracking issues individually.
