### ISSUE TITLE
prompt boxes design

### ISSUE THREAD

**Issue by open-contracts** [open-contracts/open-contracts.github.io#8]
The prompt boxes are taking up too much space right now, so just like with the function grid, I'd like to move towards a more tight and compact theme. Like, here:
![image](https://user-images.githubusercontent.com/90533597/140804748-fb27d8cb-b66f-45e4-a13d-4496f6426b1d.png)

The whole page is full with just the inputs, for no reason. It also makes no sense to duplicate all input names, types and values, and Triplicate (quadruplicate for oracleFunctions) the name of the current function. Space = user attention = scarce, and we want to make the most of it.

Once you did https://github.com/open-contracts/open-contracts.github.io/issues/6:

1. Reduce the gaps between prompt content and prompt borders for all prompts. They are huge right now. Make it more similar to what github uses e.g. here:
![image](https://user-images.githubusercontent.com/90533597/140805359-51443dd7-e5f7-418c-854c-0c06e617cfca.png)

2. Let's make it such that there is always only one input prompt, which looks much like the current 'call' prompt. 
![image](https://user-images.githubusercontent.com/90533597/140804699-10c063c2-2d76-4351-a4ef-20f93b9235b6.png)
Make it proper white, and make the borders more grey than black to make them less pronounced (there should be a contrast with the grey tab background after doing https://github.com/open-contracts/open-contracts.github.io/issues/6). I didn't like the green for something as neutral as inputs after all, we'll use it for the result. Just change the prompt title to 'input', put some light grey text fields where the current '= undefined' are, like my url bar below, to keep it minimal (no borders pls):
![image](https://user-images.githubusercontent.com/90533597/140805965-f54a8fef-2226-444b-9303-19ebf59a36e7.png)
Don't use a hover animation for the tile, just for the text fields.

3. Let's get rid of the 'Call' prompt and the 'Load Oracle' prompt (in the oracle case), and just make them compact buttons on the bottom right of the input prompt. Like the 'submit new issue' button below. In the oracle case, put the 'load oracle' button directly to the left of the 'Call Function' button on the right. The former should become and stay inactive once clicked, and the latter button should be greyed out/ inactive until the former is clicked and has completed. The former should read 'Load Oracle Data (1/4)' etc. with the counter incrementing as the load promises resolve. both buttons should be dark grey, and have the same color palette (they will look different bc only one of them is active at a time).
![image](https://user-images.githubusercontent.com/90533597/140806954-1fa3ca39-ddd4-4aa6-9821-a8ecc40fb8d2.png)

4. All other prompts should show up below the input field and the run buttons. All prompts below should be reset when clicking the 'Call Function' button. As a result, there will only ever be one error prompt at a time, referring to the current error.

5. The result should be a separate prompt, not an indented one. It should only show up if the function call succeeds. Give it the green that used to be for the input. Have its title be 'result', i.e. don't duplicate the function name. Important: make it easy to select and copy the result, right now this is not possible.

**Comment by l-monninger** [comment]
@Jonas-Metzger 2 makes me think we should just do away with inputs in the log. So, I'm going to just make things more compact first, see if you like that. Then, we can move the next.
