### ISSUE TITLE
This is what I mean by promisifying

### ISSUE THREAD

**Issue by l-monninger** [open-contracts/open-contracts.github.io#9]
https://github.com/open-contracts/open-contracts.github.io/blob/538d09bee710689514a14277526655f4b42fc0f0/protocol/opencontracts.js#L371

**Comment by l-monninger** [comment]
@Jonas-Metzger

**Comment by l-monninger** [comment]
https://github.com/open-contracts/open-contracts.github.io/blob/538d09bee710689514a14277526655f4b42fc0f0/protocol/opencontracts.js#L119 (More important here.)

**Comment by open-contracts** [comment]
closing this for now. can reopen if it becomes important again.
